### PR TITLE
CockroachDB support

### PR DESCRIPTION
**Pull request by mclark4386**
This adds CockroachDB support. Currently configs have to be separated out(no url support), see database.yml file for example. 

Also added ReplaceSchema, ReplaceColumn and DropColumn to schema query system.

Everything seems to work as intended, but please let me know if you would like me to change anything.

**Notes:**

- Cockroach doesn't currently support changing columns in a way that would alter the data in them so to make change_column work I had to make it move the current column, create the new column with the right types/details, move the data from old -> new and drop old.
- Cockroach uses pq for most things, so I had to cheat a bit with the connection details...
- Cockroach holds most data changes until the commit of a transaction so I had to move all fizz changes into separate transactions in order to make sure everything happened as laid out in the file.

### CODE REVIEW

**Comment by markbates** [comment]
Overall the code looks great! Here are a few things I ran into trying to use it:

* Update `README`
  * include the fact it supports Cockroach
  * setup instructions, if needed
  * known issues & and workarounds
* Update `config` command to generate a valid Cockroach `database.yml` file
* After running `soda migrate` the `schema dump` command fails:
```
[POP] 2018/01/06 15:07:39 cockroach dump bloggy_development --dump-mode=schema
Error: connections with user root must use a client certificate
Failed running "dump"
```

Hopefully they're all really small fixes/improvements. Once this is merged I can add support into Buffalo for it. Can't wait!

**Comment by mclark4386** [comment]
> - Update README
       - include the fact it supports Cockroach
       - setup instructions, if needed
       - known issues & and workarounds

That is easy enough, I'll see if I can't get it done on Monday.

>  - Update config command to generate a valid Cockroach database.yml file

Honestly didn't even think about that, but I'll look into it on Monday.

>    - After running soda migrate the schema dump command fails:

```
[POP] 2018/01/06 15:07:39 cockroach dump bloggy_development --dump-mode=schema
Error: connections with user root must use a client certificate
Failed running "dump"
```

That is actually something that I knew about. The trick is that if you don't have a secure cockroach cluster you have to run the commands with --insecure, but I think if you run the with --insecure against a secure cluster it borks... I left it like this be cause I figured in practice the cluster would be secure... but should probably add a config as to if it's secure or not and then reflect that in the commands... I'll look into it on Monday!

**Comment by markbates** [comment]
I would say add some way of running it in insecure more optionally. One way might be to have it in the database.yml options section and have it default to secure, but print the default in the config for development to insecure. Or something like that anyway.

**Comment by mclark4386** [comment]
Yeah, that's basically what I had in mind as well^^ Sorry this wasn't done before submitting it. Guess I got excited when I got that last bug fixed... Thanks for catching it!

**Comment by mclark4386** [comment]
So I re-used sslmode because that's basically what it is. disable == insecure. If you would rather me make a new flag I'm happy to, but this made sense to me. I'll get into the config and all the docs tomorrow^^

**Comment by mclark4386** [comment]
Ok, decided to just wrap it up. See what you think. Happy make any other changes you would like!

**Pull request merged**
