### PR TITLE
improve database migrations

### PR DESCRIPTION
**Pull request by endihunter**
1. Prepend primary key
2. Append timestamps (optionally timestamps can be disabled)
3. add useful Timestamps methods

### CODE REVIEW

**Comment by endihunter** [comment]
new argument were added to a create_table function, so the tests may fail

**Comment by endihunter** [comment]
@markbates works for mysql, but for some reason fails for sqlite & postgres - any ideas why?

**Comment by markbates** [comment]
Travis sometimes freaks out with MySQL so often if you just restart that job it'll pass. It's really annoying. :(

**Comment by endihunter** [comment]
tests passed...
to disable timestamps during the table creation - there is a t.DisableTimestamps() method

also useful methods were added: t.Timestamps(), t.Timestamp("migrated_at")

**Comment by markbates** [comment]
Awesome. Thanks!

**Pull request merged**
