### PR TITLE
add Gopkg.toml; resolves #90

### LINKED ISSUE #90: introduce dep for vendor management
We should be able to install and manage `pop` versions via `dep`, the soon-to-be integrated package manager in golang.

### PR DESCRIPTION
**Pull request by mkozjak**
Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>

### CODE REVIEW

**Comment by markbates** [comment]
@mkozjak didn't want you think I forgot about this. Having these files causes issues when generating new Buffalo apps, so those need to be resolved before this can be merge.

**Comment by mkozjak** [comment]
@markbates No problem. Looking forward to get ourselves vendored. :)

**Comment by mkozjak** [comment]
What's up with this one?

**Comment by markbates** [comment]
Still haven't resolved the issues around this. Haven't forgotten about it, but haven't fixed it yet either. :)

**Comment by markbates** [comment]
Fixed here https://github.com/markbates/pop/commit/b1f0237d112c6281debc0419205510979894ebf9

**Pull request closed without merging**
