### PR TITLE
handle url configuration for mysql properly

### PR DESCRIPTION
**Pull request by sio4**
Hello,
I request this PR for issue of mysql URL handling. (#116)

* Remove URL scheme prefix when return from `mysql.URL()`. (file: `mysql.go`)
* Parse(Finalize) URL for mysql properly. (for both old pattern and DSN patterns) (file: `connection_details.go`)
* Fixed template for `soda`. (file: `model_templates.go`)
* Add some test cases for this patch including legacy, dsn with host and port, using default port(host only), dsn has protocol, and socket. (file: `connection_details_test.go`)

Anyway, as shown in socket case, if URL is provided then parsing the URL is not required for make final URL. (because URL is already provided and it is more nice way to handle detailed configuration. we just need to get the dialect for configuration.)

And I think we can fix user provided URL if it is not fit for underlying driver but it is not a job of ORM (and/or framework). Its users. I don't like to print out some message from library or similar thing but if needed, we can simply add some warning message for mis passed URL.

### CODE REVIEW

**Comment by sio4** [comment]
Hi @markbates,

If you really really want to make any changes for existing users, I think the patch below will work for that. But it is so tricky and I think it is better that we just fix it properly not just add dirty patch, even if there will be some confusion for existing users.

The current master branch already is not working for the people using URL. So if they faced it, like me, they will try to recover it and will visit here. So my thought is, do not add tricky patch and just add some documentation of setting a URL for mysql properly.

```diff
--- a/mysql.go
+++ b/mysql.go
@@ -27,7 +27,14 @@ func (m *mysql) Details() *ConnectionDetails {
 func (m *mysql) URL() string {
        c := m.ConnectionDetails
        if m.ConnectionDetails.URL != "" {
-               return strings.TrimPrefix(m.ConnectionDetails.URL, "mysql://")
+               //! Just work-around for legacy users!!!
+               //! Remove this block when next major upgrade!
+               if strings.Contains(c.URL, "(") {
+                       return strings.TrimPrefix(c.URL, "mysql://")
+               } else if c.Host != "" {
+                       ul := strings.TrimPrefix(c.URL, "mysql://")
+                       return strings.Replace(ul, c.Host+":"+c.Port, "("+c.Host+":"+c.Port+")", 1)
+               }
        }
        s := "%s:%s@(%s:%s)/%s?parseTime=true&multiStatements=true&readTimeout=1s"
        return fmt.Sprintf(s, c.User, c.Password, c.Host, c.Port, c.Database)
```

**Comment by sio4** [comment]
Hello @markbates ,
Do not merge it yet.
I finally tested with this PR and when I tried with additional parameters with `?parameter1=value1&...` the `&` is converted to `&amp;` so it is not working. I will totally review this code and then update soon.

Please wait until final test.

**Comment by sio4** [comment]
I found the `&` in `url` was converted to `&amp;` while parsing yaml configuration file as template.
I changed `html/template` to `text/template` to prevent URL escaping. (the configuration file is originally not an HTML so it works fine.)

For the more, I added two more changes:
* Changed `Test_ConnectionDetails_Finalize_MySQL_Legacy` with more detailed arguments.
* Changed `soda` template for MySQL with default parameters so User can start with default values.
  (it will reduce some initial troubles for them; like time conversion.)

**Comment by markbates** [comment]
Great work! Thanks so much!

**Comment by sio4** [comment]
Thanks so much too!

**Pull request merged**
