### PR TITLE
Moving generator to inflect

### PR DESCRIPTION
**Pull request by paganotoni**
This pr moves the pop model generator to use inflect.Name, it also solves 1 issue I found on the generator when running:

```sh
buffalo g r myTable name otherID:uuid
```

Generated migration added otherID field as

```
...
t.Column("otherID", "uuid", {})
...
```

Instead of 

```
...
t.Column("other_id", "uuid", {})
...
```

### CODE REVIEW

**Comment by markbates** [comment]
@paganotoni looks like there are some merge conflicts, can you resolve?

**Comment by paganotoni** [comment]
@markbates all set, conflicts solved.

**Comment by markbates** [comment]
The validations on the model didn't get generated correctly:

```
$ buffalo db g model user name admin:bool price:float widgetID:uuid
```

```go
// Validate gets run every time you call a "pop.Validate*" (pop.ValidateAndSave, pop.ValidateAndCreate, pop.ValidateAndUpdate) method.
// This method is not required and may be deleted.
func (u *User) Validate(tx *pop.Connection) (*validate.Errors, error) {
	return validate.Validate(
		&validators.StringIsPresent{Field: u.name, Name: "name"},
	), nil
}
```

**Comment by paganotoni** [comment]
Ouch, Thanks @markbates, I'll get that one covered.

**Comment by paganotoni** [comment]
@markbates I've covered that one as well as an issue with the plural being generated in lowercase, please give it a shot when you have the chance, thanks!

**Comment by paganotoni** [comment]
Yay! Thanks, @markbates!

**Pull request merged**
