### PR TITLE
[MySQL] Use SQL instead of mysql client for create and drop DB

### PR DESCRIPTION
**Pull request by stanislas-m**
* db create & db drop can be used without MySQL client

### CODE REVIEW

**Comment by stanislas-m** [comment]
Ping @markbates

**Comment by markbates** [comment]
I'm having trouble running this on a fresh system:

```
$ soda create -a -d

[POP]: Loading config file from /Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/database.yml
[POP] 2017/10/18 10:29:36 Create coke_development (root:root@(localhost:3306)/coke_development?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2017/10/18 10:29:36 CREATE DATABASE `coke_development` DEFAULT COLLATE `utf8_general_ci`
created database coke_development
[POP] 2017/10/18 10:29:36 Create coke_test (root:root@(localhost:3306)/coke_test?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2017/10/18 10:29:36 CREATE DATABASE `coke_test` DEFAULT COLLATE `utf8_general_ci`
Error: couldn't create database coke_test: error creating MySQL database coke_test: Error 1049: Unknown database 'coke_test'
Usage:
  soda create [flags]

Flags:
  -a, --all    Creates all of the databases in the database.yml
  -h, --help   help for create

Global Flags:
  -c, --config string   The configuration file you would like to use.
  -d, --debug           Use debug/verbose mode
  -e, --env string      The environment you want to run migrations against. Will use $GO_ENV if set. (default "development")
  -p, --path string     Path to the migrations folder (default "./migrations")

couldn't create database coke_test: error creating MySQL database coke_test: Error 1049: Unknown database 'coke_test'
```

**Comment by stanislas-m** [comment]
Damn, good catch!

**Comment by stanislas-m** [comment]
@markbates It should work, now. :)

**Comment by markbates** [comment]
Thanks @stanislas-m

**Pull request merged**
